name: flutter_mobx_graphql
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.13.1 <3.0.0'
  flutter: 2.2.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  cached_network_image: ^3.0.0
  google_fonts: ^2.1.0

  # TODO: Remove from starter project
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  provider: ^5.0.0
  graphql: ^5.0.0
  either_dart: ^0.1.2
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # TODO: Remove from starter project
  mockito: ^5.0.10
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.5
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
